### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by shaonturaj** [recitativonika/kaisar-zero-node-bot#2]
Does proxy work? I am confused can you check below if my settings is incorrect? 

![Screenshot_20241128_204639_Termius](https://github.com/user-attachments/assets/c642c171-b59c-45fa-b0b1-7f0725e97d16)

It shows like this where my account format  is 

miningelectro********@gmail.com, ***** , http://dnsgqwky:*****@102.212.90.65:5759

This is a single entry in a single line
(* are the passwords)

**Comment by recitativonika** [comment]
if I look in your data, it have spacing every comma, can you try delete it?

`miningelectro********@gmail.com, ***** , http://dnsgqwky:*****@102.212.90.65:5759/`
to
`miningelectro********@gmail.com,*****,http://dnsgqwky:*****@102.212.90.65:5759/`

and it looks like you're running the wrong script too, you have to run `setup.js` first and then `index.js` . Please read the readme again carefully.
let me know if it still error or not.

**Comment by shaonturaj** [comment]
Theres no gap i have checked.. Its still not working. Without proxy its working perfectly but with proxy yes its not working

**Comment by recitativonika** [comment]
That weird, can you send me your account data in `data.txt`? but hide the important thing.

**Comment by shaonturaj** [comment]
mining@gmail.com,****,http://dnsgqwky:gygb@102.212.90.65:5759

this is inside my data file

**Comment by recitativonika** [comment]
> [mining@gmail.com](mailto:mining@gmail.com),****,http://dnsgqwky:gygb@102.212.90.65:5759
> 
> this is inside my data file

i think that is for `user.txt`, the `data.txt` should look like this for example:

```
email1,token1,extensionid1,proxy1
```
```
gxxxx@xxx.com,eyJhbGciOiJIUzxxxxx,a8f8xxxxx,http://sxxx:o8xxxl@161.xxx.115:6xxx
```

what you send is `email,password,proxy`. You must put that in `user.txt` and then run `node setup.js` not index.js, it will fill the data.txt automatically. After run setup, then you run the `node index.js`

Please clear all the text in `data.txt` and fill your account,password,proxy in `user.txt`

**Comment by shaonturaj** [comment]
Bravo! Genius! 
 Okay now its working 

Thanks 

Can you have a look on Mitosis Incentivized testnet?  It will run for 30 days only started from today and Its incentivized. Task is to interact with dapps and make tx. You gonna better understand than me. If possible please have look on that. :)

**Comment by recitativonika** [comment]
Maybe I will look into that when I have time.
